### ISSUE TITLE
Add option to ouput size into MB

### ISSUE THREAD

**Issue by regexgreg** [idiv-biodiversity/mmdu#3]
Please add option to output size into MB or K or some standard size? The summarized or Human readable output is not always predictable.

I have some folder reporting P sizes when they are no where near those sizes.
My guess is when your code adds all the summarized sizes (which are probably rounded off), it comes up with these bazaar numbers

**Comment by wookietreiber** [comment]
Please provide an example with the outputs of:

```bash
mmdu /path/to/dir
du -sh /path/to/dir
```
